[package]
name = "rust-practice"
version = "0.1.0"
authors = ["Akira Sosa <akirasosa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert_cli = "0.6.3"

